# Generated by Django 5.1.3 on 2024-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="animal_type",
            field=models.CharField(help_text="Type of animal spotted", max_length=255),
        ),
        migrations.AlterField(
            model_name="report",
            name="description",
            field=models.TextField(help_text="Description of the sighting"),
        ),
        migrations.AlterField(
            model_name="report",
            name="location",
            field=models.CharField(
                help_text="Geolocation of the sighting", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="photo_url",
            field=models.URLField(
                blank=True, help_text="url  of the uploaded photo", null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Resolved", "Resolved"),
                    ("Escalated", "Escalated"),
                ],
                default="Pending",
                help_text="Current status of the report",
                max_length=50,
            ),
        ),
    ]
